layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  include_stars: false
  include_forks: false
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: xsalazar3
  # keybase: your_username
  linkedin: xsalazar
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Firebase
    web_url: https://github.com/topics/firebase
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/firebase/firebase.png

  - name: Terraform
    web_url: https://github.com/topics/terraform
    image_url: https://www.terraform.io/assets/images/og-image-8b3e4f7d.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png

# SEO
title: Xavier Salazar
author: Xavier Salazar
logo: assets/logo.png
description: Software engineer from the Pacific Northwest. My mom's favorite programmer. 👨‍💻 My dog's favorite photographer. 📸🐶
url: https://xsalazar.com
social:
  name: Xavier Salazar
  links:
    - https://instagram.com/xsalazar3
    - https://linkedin.com/in/xsalazar
    - https://github.com/xsalazar
webmaster_verifications:
  google: GJibD157tlD6Fe2zteRZEYkH8pfFJSXJiFJikp5_A6w