name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Download Resume 📜
        uses: xsalazar/actions/downloader@master
        with:
          url: ${{ secrets.RESUME_URL }}
          filename: "public/resume.pdf"

      - name: Download Terraform Certification 💾
        uses: xsalazar/actions/downloader@master
        with:
          url: ${{ secrets.TERRAFORM_CERTIFICATION_URL }}
          filename: "public/terraform-cert.pdf"

      - name: Download AWS Certification 💾
        uses: xsalazar/actions/downloader@master
        with:
          url: ${{ secrets.AWS_CERTIFICATION_URL }}
          filename: "public/aws-cert.pdf"

      - name: Setup Node 🏗
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: build
          CLEAN: true # Automatically remove deleted files from the deploy branch
