name: Build GitHub Page

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Build Page
      uses: xsalazar/actions/pages-build@master
      with:
        username: ${{ github.actor }}
        api_token: ${{ secrets.API_TOKEN }}
