on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Page
      uses: xsalazar/actions/pages-build@master
      with:
        username: ${{ github.actor }}
        api_token: ${{ secrets.API_TOKEN }}
    - name: Download Resume
      uses: xsalazar/actions/downloader@master
      with:
        url: ${{ secrets.RESUME_URL }}
        filename: 'resume.pdf'
